version: "3.8"

services:
  pregen-api:
    build: .
    container_name: pregen-api
    environment:
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
      ALLOWED_ORIGINS: '["https://www.example.com","https://api.example.com"]'
    ports:
      - '8000:8000'
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: "no"
    secrets:
      - openai_api_key
    networks:
      - pregen-net

secrets:
  openai_api_key:
    file: openai_api_key.txt

networks:
  pregen-net: {}